export const PLANTS = [
  {
    id: 1,
    name: 'GOIANIA (GYN)',
    city: 'GOIANIA',
    state: 'GO',
    street: 'Rua Iza Costa, 01',
    bu: 'GEOS Fábrica',
    enterprise: 'FIBI',
    distance: 928,
    leadTime: 12,
  },
  {
    id: 2,
    name: 'ITUMBIARA (ITB)',
    city: 'ITUMBIARA',
    state: 'GO',
    street: 'Rod BR 153, km 1475',
    bu: 'GEOS Fábrica',
    enterprise: 'FIBI',
    distance: 711,
    leadTime: 9,
  },
  {
    id: 3,
    name: 'MAIRINQUE (MRK)',
    city: 'MAIRINQUE',
    state: 'SP',
    street: 'Av. Cargill, s/nº',
    bu: 'GEOS Fábrica',
    enterprise: 'FIBI',
    distance: 93,
    leadTime: 2,
  },
  {
    id: 4,
    name: 'ILHÉUS (IOS)',
    city: 'ILHÉUS',
    state: 'BA',
    street: 'Rod. Ilhéus-Uruçuca, S/N',
    bu: 'COCOA Fábrica',
    enterprise: 'FIBI',
    distance: 1718,
    leadTime: 72,
  },
  {
    id: 5,
    name: 'PORTO FERREIRA (POF)',
    city: 'PORTO FERREIRA',
    state: 'SP',
    street: 'AV. RUDOLF STREEIT, 55',
    bu: 'COCOA Fábrica',
    enterprise: 'FIBI',
    distance: 246,
    leadTime: 3,
  },
  {
    id: 6,
    name: 'INNOVATTI (CIS)',
    city: 'MAIRINQUE',
    state: 'SP',
    street: 'Av. Antonio Oliveira Santos, s/n',
    bu: 'CBI Fábrica',
    enterprise: 'FIBI',
    distance: 94,
    leadTime: 2,
  },
  {
    id: 7,
    name: 'CBI (antiga SGS)',
    city: 'PONTA GROSSA',
    state: 'PR',
    street: 'RUA ANA SCREMIN,939',
    bu: 'CBI Fábrica',
    enterprise: 'FIBI',
    distance: 560,
    leadTime: 8,
  },
  {
    id: 8,
    name: 'UBERLÂNDIA (ULA) ÁCIDO CÍTRICO',
    city: 'UBERLÂNDIA',
    state: 'MG',
    street: '',
    bu: 'CBI Fábrica',
    enterprise: 'FIBI',
    distance: 612,
    leadTime: 8,
  },
  {
    id: 9,
    name: 'CASTRO (CST)',
    city: 'CASTRO',
    state: 'PR',
    street: 'Rod PR 090 , CX Postal 1001 – CEP: 84166-981',
    bu: 'STARCHES & SWEETENERS Fábrica',
    enterprise: 'FIBI',
    distance: 481,
    leadTime: 9,
  },
  {
    id: 10,
    name: 'UBERLÂNDIA (ULA) MILHO',
    city: 'UBERLÂNDIA',
    state: 'MG',
    street: '',
    bu: 'STARCHES & SWEETENERS Fábrica',
    enterprise: 'FIBI',
    distance: 612,
    leadTime: 8,
  },
  {
    id: 11,
    name: 'BARREIRAS (BRS)',
    city: 'BARREIRAS',
    state: 'BA',
    street: 'BR 020/242 KM 604',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 1610,
    leadTime: 72,
  },
  {
    id: 12,
    name: 'PONTA GROSSA (PGO)',
    city: 'PONTA GROSSA',
    state: 'PR',
    street: 'BR 376 Km 506',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 885,
    leadTime: 8,
  },
  {
    id: 13,
    name: 'PRIMAVERA DO LESTE (PDL)',
    city: 'PRIMAVERA DO LESTE',
    state: 'MT',
    street: 'Rod BR 070 s/n - KM 286',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 1457,
    leadTime: 72,
  },
  {
    id: 14,
    name: 'RIO VERDE (RVE)',
    city: 'RIO VERDE',
    state: 'GO',
    street: 'ROD. ESTADUAL ANEL VIARIO FAZENDA SAO THOMAZ ABOBORAS',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 927,
    leadTime: 48,
  },
  {
    id: 15,
    name: 'TRÊS LAGOAS (TLG)',
    city: 'TRÊS LAGOAS',
    state: 'MS',
    street: 'Rua: Egidio Thome, 5700',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 682,
    leadTime: 8,
  },
  {
    id: 16,
    name: 'UBERLÂNDIA (ULA)',
    city: 'UBERLÂNDIA',
    state: 'MG',
    street: '',
    bu: 'CASC Fábrica',
    enterprise: 'CASC',
    distance: 612,
    leadTime: 8,
  },
  {
    id: 17,
    name: 'PARANAGUÁ (PGA)',
    city: 'PARANAGUÁ',
    state: 'PR',
    street: 'Av. Portuária, s/nº',
    bu: 'CASC Porto',
    enterprise: 'CASC',
    distance: 502,
    leadTime: 7,
  },
  {
    id: 18,
    name: 'SANTARÉM (STM)',
    city: 'SANTARÉM',
    state: 'PA',
    street: 'AV. Cuiaba, s/n Lote 04 CDP',
    bu: 'CASC Porto',
    enterprise: 'CASC',
    distance: 3342,
    leadTime: 168,
  },
  {
    id: 19,
    name: 'MIRITITUBA (MTB)',
    city: 'MIRITITUBA',
    state: 'PA',
    street: 'End: MARGEM DIREITA DO RIO TAPAJOS, S/N',
    bu: 'CASC Porto',
    enterprise: 'CASC',
    distance: 3042,
    leadTime: 168,
  },
  {
    id: 20,
    name: 'PORTO VELHO (PVH)',
    city: 'PORTO VELHO',
    state: 'RO',
    street: 'Estr Fazenda dos Milagres, 26 - ',
    bu: 'CASC Porto',
    enterprise: 'CASC',
    distance: 3046,
    leadTime: 144,
  },
  {
    id: 21,
    name: 'TEG',
    city: 'GUARUJÁ',
    state: 'SP',
    street: 'Av. Bento Pedro da Costa, 65',
    bu: 'CASC Porto (joint venture)',
    enterprise: 'CASC',
    distance: 111,
    leadTime: 2,
  },
  {
    id: 22,
    name: 'BEBEDOURO',
    city: 'BEBEDOURO',
    state: 'SP',
    street: 'SP 322',
    bu: 'Fábrica',
    enterprise: 'Fábrica',
    distance: 406,
    leadTime: 5,
  },
]

export const PRICE_PER_KM = 3.4;

const GRIS = 0.1;
const ADVALOREM = 0.15;

export const GRIS_ADVALOREM = GRIS + ADVALOREM;

export const TAX = 12;